<?php

// autoload_static.php @generated by Composer

namespace Composer\Autoload;

class ComposerStaticInit90a9e42279133ab7039ffef6046249d4
{
    public static $prefixLengthsPsr4 = array (
        't' => 
        array (
            'thiagoalessio\\TesseractOCR\\' => 27,
        ),
        'P' => 
        array (
            'PHPShopify\\' => 11,
        ),
    );

    public static $prefixDirsPsr4 = array (
        'thiagoalessio\\TesseractOCR\\' => 
        array (
            0 => __DIR__ . '/..' . '/thiagoalessio/tesseract_ocr/src',
        ),
        'PHPShopify\\' => 
        array (
            0 => __DIR__ . '/..' . '/phpclassic/php-shopify/lib',
        ),
    );

    public static $classMap = array (
        'Composer\\InstalledVersions' => __DIR__ . '/..' . '/composer/InstalledVersions.php',
    );

    public static function getInitializer(ClassLoader $loader)
    {
        return \Closure::bind(function () use ($loader) {
            $loader->prefixLengthsPsr4 = ComposerStaticInit90a9e42279133ab7039ffef6046249d4::$prefixLengthsPsr4;
            $loader->prefixDirsPsr4 = ComposerStaticInit90a9e42279133ab7039ffef6046249d4::$prefixDirsPsr4;
            $loader->classMap = ComposerStaticInit90a9e42279133ab7039ffef6046249d4::$classMap;

        }, null, ClassLoader::class);
    }
}
